###features
levels.features.chasm.chasm=深淵
levels.features.chasm.yes=是的，我知道我在做什麼
levels.features.chasm.no=不，我改主意了
levels.features.chasm.jump=你確定要跳入深淵中?從這麼高的地方摔下去一定很疼。
levels.features.chasm.ondeath=你落地過猛摔死了……
levels.features.chasm.rankings_desc=死於撞擊



###rooms
levels.rooms.special.magicalfireroom$eternalfire.desc=這裡有一堵亮綠色的火牆，絕對是魔法造物。那些火十分密集，不僅無法穿過，還會點燃任何靠近它的東西。它似乎沒有熄滅的跡象，你需要用一些東西來熄滅它。

levels.rooms.special.sentryroom$sentry.name=血色哨衛
levels.rooms.special.sentryroom$sentry.desc=這紅似鮮血的哨衛結晶像是被刻意安置在此，守衛著房間另一端的寶藏。如果你進入警戒區域，它就會向你發射解離光束。\n\n它對所有的負面效果都免疫，能一眼看穿隱身效果，但似乎需要充能一段時間才能開火。\n\n不知何故，哨兵只會向你開火，就好像它知道地城裡的居民對寶藏沒有威脅一樣。
levels.rooms.special.sentryroom$sentry.discover_hint=此敵人在地下城各區皆有可能出現。

levels.rooms.special.toxicgasroom$toxicvent.name=毒氣排孔
levels.rooms.special.toxicgasroom$toxicvent.desc=一定是一個莽撞的冒險家在很久以前觸發了這個陷阱。儘管處於不活躍狀態，它仍在向房間中噴射有毒氣體，而且沒有停止的跡象。想要探索這個房間，你必須得想想辦法避免毒氣的傷害。

levels.rooms.special.weakfloorroom$hiddenwell.name=遠處的井
levels.rooms.special.weakfloorroom$hiddenwell.desc=你隱約可以看到深處有一口井，也許這下面有些什麼?


levels.rooms.quest.blacksmithroom$questentrance.name=礦坑入口
levels.rooms.quest.blacksmithroom$questentrance.desc=這架梯子通往鐵匠鋪下方的一座老舊礦坑。



levels.rooms.quest.mineentrance$questexit.name=礦坑出口
levels.rooms.quest.mineentrance$questexit.desc=這架梯子通往礦坑的出口，連通回鐵匠鋪。

###traps
levels.traps.alarmtrap.name=警報陷阱
levels.traps.alarmtrap.alarm=陷阱產生的尖銳的警報聲在地下城裡迴盪!
levels.traps.alarmtrap.desc=這個陷阱看起來有著能發出巨響的機制。觸發它將使本層所有生物對這裡產生警覺。

levels.traps.burningtrap.name=烈焰陷阱
levels.traps.burningtrap.desc=踩進這個陷阱會點燃某種化學混合物，導致周圍小塊區域起火。

levels.traps.cursingtrap.name=詛咒陷阱
levels.traps.cursingtrap.curse=你的某件裝備被詛咒了!
levels.traps.cursingtrap.desc=這個陷阱充滿了詛咒的力量。觸發它會詛咒你身上的部分裝備。

levels.traps.explosivetrap.name=爆炸陷阱
levels.traps.explosivetrap.desc=這個陷阱包含一些粉狀炸藥和一個觸發機制。觸發它會導致一定範圍的爆炸。

levels.traps.flocktrap.name=羊群陷阱
levels.traps.flocktrap.desc=也許是個來自一些業餘法師的玩笑，觸發這個陷阱就會召喚一群魔法綿羊。

levels.traps.miningrockfalltrap.name=礦區落石陷阱
levels.traps.miningrockfalltrap.ondeath=你被礦區落石砸扁了……
levels.traps.miningrockfalltrap.desc=這個礦區陷阱會讓周圍5x5範圍內的岩石墜落。鬆軟的岩石傷害低於完整塌方，但會無視護甲；緊鄰支架的區域則受到保護。\n\n_這個陷阱無法辨別敵友。_

levels.traps.summoningtrap.name=召喚陷阱
levels.traps.summoningtrap.desc=觸發這個陷阱將召喚本區域的一些怪物到這裡。

levels.traps.teleportationtrap.name=傳送陷阱
levels.traps.teleportationtrap.desc=當這種陷阱被觸發時，其周遭的所有東西都會被各自傳送到這一層的隨機地點。


levels.traps.trap.discover_hint=你可以在這個五層地下城中隨機找到這種陷阱。
levels.traps.trap.rankings_desc=死於%s

levels.traps.worndarttrap.name=老化的飛鏢陷阱
levels.traps.worndarttrap.ondeath=你被老化的飛鏢陷阱射殺……
levels.traps.worndarttrap.desc=一個小型飛鏢發射器一定隱藏在附近，激活這個陷阱將導致它向最近的目標射出一枚飛鏢。\n\n年久失修導致它並不怎麼危險，其觸發機關甚至沒有被隱藏起來……



###levels







levels.level.hidden_trap=一個隱藏的%s被觸發了!
levels.level.chasm_name=深淵
levels.level.floor_name=地板
levels.level.grass_name=草
levels.level.water_name=水
levels.level.wall_name=牆壁
levels.level.closed_door_name=關著的門
levels.level.open_door_name=開著的門
levels.level.entrace_name=樓層入口
levels.level.exit_name=樓層出口
levels.level.embers_name=灰燼
levels.level.furrowed_grass_name=枯萎的植物
levels.level.locked_door_name=鎖著的門
levels.level.crystal_door_name=水晶門
levels.level.pedestal_name=基座
levels.level.barricade_name=路障
levels.level.high_grass_name=高草
levels.level.locked_exit_name=鎖著的樓層出口
levels.level.unlocked_exit_name=開放的樓層出口
levels.level.well_name=井
levels.level.empty_well_name=乾涸的井
levels.level.statue_name=雕像
levels.level.inactive_trap_name=已觸發的陷阱
levels.level.bookshelf_name=書架
levels.level.alchemy_name=煉金釜
levels.level.default_name=???
levels.level.chasm_desc=你看不到底。
levels.level.water_desc=著火時踏進水裡即可滅火。
levels.level.entrance_desc=通向上一層的樓梯。
levels.level.exit_desc=通向下一層的樓梯。
levels.level.embers_desc=灰燼覆蓋著地板。
levels.level.high_grass_desc=茂密的植被阻擋了視線。
levels.level.locked_door_desc=這門被鎖上了，你需要匹配的鑰匙來打開。
levels.level.crystal_door_desc=這扇上鎖的門是由魔法水晶製成的。你甚至能看到對面，但你還是需要一把水晶鑰匙才能打開它。
levels.level.locked_exit_desc=沉重的鐵欄杆封鎖住了下樓樓梯。
levels.level.barricade_desc=木柵欄依然堅固，但早已風乾多年。燒了怎麼樣?
levels.level.inactive_trap_desc=這個陷阱已經被觸發過了，現在一點也不危險。
levels.level.statue_desc=有人想裝飾一下這裡，但很顯然這裝飾實在是爛透了。
levels.level.alchemy_desc=這口煉金釜中充滿了魔力之水。 物品可以在裡面共鍊以製造新的物品。
levels.level.empty_well_desc=這座井已經枯竭了。

levels.level$feeling.chasm_title=空洞樓層
levels.level$feeling.water_title=含水樓層
levels.level$feeling.grass_title=繁茂樓層
levels.level$feeling.dark_title=暗黑樓層
levels.level$feeling.large_title=大型樓層
levels.level$feeling.traps_title=陷阱樓層
levels.level$feeling.secrets_title=神秘樓層
levels.level$feeling.chasm_desc=你的腳步聲迴盪在虛空中。
levels.level$feeling.water_desc=你聽見周圍水花的聲音。
levels.level$feeling.grass_desc=空氣中瀰漫著濃郁的植物清香。
levels.level$feeling.dark_desc=你依稀能聽到敵人在黑暗中潛伏。
levels.level$feeling.large_desc=這一層的規模貌似格外龐大。
levels.level$feeling.traps_desc=這一層的地面上機關密布，殺意凜然。
levels.level$feeling.secrets_desc=詭異的氣氛正暗示這層隱藏著很多祕密。

levels.mininglevel.wall_desc=這裡光滑的岩壁比上面的更軟一些。你可以用你的礦鎬挖它，但這需要些花些體力，飢餓值也會明顯提升。
levels.mininglevel.gold_extra_desc=你或許可以用礦鎬把它挖出來。
levels.mininglevel.crystal_name=水晶尖刺
levels.mininglevel.boulder_name=岩礫
levels.mininglevel.crystal_desc=這裡冒出了一塊巨大的水晶，這種脆弱的物質只要被礦鎬挖掘或鄰近的東西被破壞就會被粉碎。
levels.mininglevel.boulder_desc=這塊巨大的石塊擋住了去路。用礦鎬應該能把它輕易弄碎。
levels.mininglevel.barricade_desc=這些木頭被牢固的固定在礦坑中支撐著。\n\n這些或許是豺狼人建來防止落石嚴重坍方的。_在其附近的落石都會失效。_\n\n像其它木製品一樣，這些支柱應該是易燃物。


levels.sewerlevel.water_name=渾濁水潭
levels.sewerlevel.empty_deco_desc=潮濕的黃綠色苔蘚覆蓋著地板。
levels.sewerlevel.bookshelf_desc=這個書架塞滿了沒用的成功學書籍。燒掉怎麼樣?
levels.sewerlevel.region_deco_name=儲物木桶
levels.sewerlevel.region_deco_desc=高度過肩的木桶。用盡力氣也無法推動，感覺裡面裝滿了東西。
