###features
levels.features.chasm.chasm=Chasm
levels.features.chasm.yes=Yes, I know what I'm doing
levels.features.chasm.no=No, I changed my mind
levels.features.chasm.jump=Do you really want to jump into the chasm? A fall that far will be painful.
levels.features.chasm.ondeath=You fell to death...
levels.features.chasm.rankings_desc=Died on Impact



###rooms
levels.rooms.special.magicalfireroom$eternalfire.desc=A wall of dense bright green fire is here, seemingly caused by magic. It's so dense that you can't move through it, and it ignites anything that gets too close. It shows no signs of burning down naturally, you'll need to use something to extinguish it.

levels.rooms.special.sentryroom$sentry.name=red sentry
levels.rooms.special.sentryroom$sentry.desc=This blood-red sentry seems to be positioned here to guard the treasure at the other end of this room. It will fire beams of disintegration magic at you if you step in the area it defends.\n\nIt's immune to all harmful effects and can see through invisibility, but seems to take a while to charge up before it starts firing.\n\nSomehow the sentry only wants to fire on you, as if it knows that the denizens of the dungeon are no threat to the treasure.
levels.rooms.special.sentryroom$sentry.discover_hint=You can find this enemy anywhere in the dungeon.

levels.rooms.special.toxicgasroom$toxicvent.name=toxic vent
levels.rooms.special.toxicgasroom$toxicvent.desc=A careless adventurer must have triggered this trap ages ago. Despite its inactive state, it's still spewing toxic gas into the room and shows no signs of stopping. You'll need some way to prevent damage from the gas if you want to explore this room.

levels.rooms.special.weakfloorroom$hiddenwell.name=Distant well
levels.rooms.special.weakfloorroom$hiddenwell.desc=You can just make out a well in the depths below, perhaps there is something down there?


levels.rooms.quest.blacksmithroom$questentrance.name=Mine entrance
levels.rooms.quest.blacksmithroom$questentrance.desc=This ladder leads to an old mine just below the blacksmith's workshop.



levels.rooms.quest.mineentrance$questexit.name=Mine exit
levels.rooms.quest.mineentrance$questexit.desc=This ladder leads out of the mine, back into the blacksmith's workshop.

###traps
levels.traps.alarmtrap.name=alarm trap
levels.traps.alarmtrap.alarm=The trap emits a piercing sound that echoes throughout the dungeon!
levels.traps.alarmtrap.desc=This trap seems to be tied to a loud alarm mechanism. Triggering it will likely alert everything on the level.

levels.traps.burningtrap.name=burning trap
levels.traps.burningtrap.desc=Stepping on this trap will ignite a chemical mixture, setting the surrounding area aflame.

levels.traps.cursingtrap.name=cursing trap
levels.traps.cursingtrap.curse=Your worn equipment becomes cursed!
levels.traps.cursingtrap.desc=This trap contains the same malevolent magic found in cursed equipment. Triggering it will curse some items in the immediate area.

levels.traps.explosivetrap.name=explosive trap
levels.traps.explosivetrap.desc=This trap contains some powdered explosive and a trigger mechanism. Activating it will cause an explosion in the immediate area.

levels.traps.flocktrap.name=flock trap
levels.traps.flocktrap.desc=Perhaps a joke from some amateur mage, triggering this trap will create a flock of magical sheep.

levels.traps.miningrockfalltrap.name=mining rockfall trap
levels.traps.miningrockfalltrap.ondeath=You were crushed by the mining rockfall trap...
levels.traps.miningrockfalltrap.desc=This mining trap loosens rocks in a 5x5 area around it. The softer stone deals less damage than a full cave-in but ignores armor, and supported cells next to barricades remain safe.\n\n_The trap cannot distinguish friend from foe._

levels.traps.summoningtrap.name=summoning trap
levels.traps.summoningtrap.desc=Triggering this trap will summon a number of this area's monsters to this location.

levels.traps.teleportationtrap.name=teleportation trap
levels.traps.teleportationtrap.desc=Whenever this trap is triggered, everything around it will be teleported to random locations on this floor.


levels.traps.trap.discover_hint=You can find this trap randomly in the five-level dungeon.
levels.traps.trap.rankings_desc=Killed by: %s

levels.traps.worndarttrap.name=worn dart trap
levels.traps.worndarttrap.ondeath=You were killed by the worn dart trap...
levels.traps.worndarttrap.desc=A small dart-blower must be hidden nearby, activating this trap will cause it to shoot at the nearest target.\n\nDue to its age it's not very harmful though, it isn't even hidden...



###levels







levels.level.hidden_trap=A hidden %s activates!
levels.level.chasm_name=Chasm
levels.level.floor_name=Floor
levels.level.grass_name=Grass
levels.level.water_name=Water
levels.level.wall_name=Wall
levels.level.closed_door_name=Closed door
levels.level.open_door_name=Open door
levels.level.entrace_name=Depth entrance
levels.level.exit_name=Depth exit
levels.level.embers_name=Embers
levels.level.furrowed_grass_name=Furrowed vegetation
levels.level.locked_door_name=Locked door
levels.level.crystal_door_name=Crystal door
levels.level.pedestal_name=Pedestal
levels.level.barricade_name=Barricade
levels.level.high_grass_name=High grass
levels.level.locked_exit_name=Locked depth exit
levels.level.unlocked_exit_name=Unlocked depth exit
levels.level.well_name=Well
levels.level.empty_well_name=Empty well
levels.level.statue_name=Statue
levels.level.inactive_trap_name=Triggered trap
levels.level.bookshelf_name=Bookshelf
levels.level.alchemy_name=Alchemy pot
levels.level.default_name=???
levels.level.chasm_desc=You can't see the bottom.
levels.level.water_desc=In case of burning step into the water to extinguish the fire.
levels.level.entrance_desc=Stairs lead up to the upper depth.
levels.level.exit_desc=Stairs lead down to the lower depth.
levels.level.embers_desc=Embers cover the floor.
levels.level.high_grass_desc=Dense vegetation blocks the view.
levels.level.locked_door_desc=This door is locked, you need a matching key to unlock it.
levels.level.crystal_door_desc=This locked door is made of magical crystal. You can see through, but you'll need a crystal key to open it.
levels.level.locked_exit_desc=Heavy bars block the stairs leading down.
levels.level.barricade_desc=The wooden barricade is firmly set but has dried over the years. Might it burn?
levels.level.inactive_trap_desc=The trap has been triggered before and it's not dangerous anymore.
levels.level.statue_desc=Someone wanted to adorn this place, but failed, obviously.
levels.level.alchemy_desc=This pot is filled with magical water. Items can be mixed into the pot to create something new!
levels.level.empty_well_desc=The well has run dry.

levels.regionvariant$chasm.title=chasm floor
levels.regionvariant$water.title=water floor
levels.regionvariant$grass.title=grass floor
levels.regionvariant$dark.title=dark floor
levels.regionvariant$large.title=large floor
levels.regionvariant$traps.title=traps floor
levels.regionvariant$secrets.title=secrets floor
levels.regionvariant$chasm.desc=Your steps echo across the dungeon.
levels.regionvariant$water.desc=You hear water splashing around you.
levels.regionvariant$grass.desc=The smell of vegetation is thick in the air.
levels.regionvariant$dark.desc=You can hear enemies moving in the darkness.
levels.regionvariant$large.desc=This dungeon floor seems unusually large.
levels.regionvariant$traps.desc=The ground seems especially treacherous here.
levels.regionvariant$secrets.desc=The atmosphere hints that this floor hides many secrets.

levels.mininglevel.wall_desc=A smooth rock wall that's a little softer than usual. You can mine through it with your pickaxe, but it'll take some effort and increase your hunger a bit.
levels.mininglevel.gold_extra_desc=You can probably mine it out with your pickaxe.
levels.mininglevel.crystal_name=Crystal spike
levels.mininglevel.boulder_name=Boulder
levels.mininglevel.crystal_desc=There is a large and colorful crystal outcropping here. These crystals are fragile and can easily be broken with a pickaxe, or will break if something is mined next to it.
levels.mininglevel.boulder_desc=There is a large boulder blocking the way. It should be fairly easy to break with a pickaxe.
levels.mininglevel.barricade_desc=The wooden barricade is firmly set and acts as a support for the ceiling.\n\nThis was probably constructed by the gnolls to give some protection against falling rocks. _Any adjacent cells will be protected from rockfall traps and attacks._\n\nIt looks like it would burn just as well as any other barricade.


levels.sewerlevel.water_name=Murky water
levels.sewerlevel.empty_deco_desc=Wet yellowish moss covers the floor.
levels.sewerlevel.bookshelf_desc=The bookshelf is packed with cheap useless books. Might it burn?
levels.sewerlevel.region_deco_name=Storage barrel
levels.sewerlevel.region_deco_desc=A stout barrel that's almost as big as you are. It must be full of something or another, it's too heavy to move.
