journal.bestiary.regional.title=區域敵人
journal.bestiary.bosses.title=頭目及其手下
journal.bestiary.universal.title=全局敵人
journal.bestiary.rare.title=稀有敵人
journal.bestiary.quest.title=任務相關敵人
journal.bestiary.neutral.title=中立角色
journal.bestiary.ally.title=盟友
journal.bestiary.trap.title=陷阱
journal.bestiary.plant.title=植物

journal.catalog.melee_weapons.title=近戰武器
journal.catalog.armor.title=護甲
journal.catalog.enchantments.title=附魔
journal.catalog.glyphs.title=刻印
journal.catalog.thrown_weapons.title=投擲武器
journal.catalog.wands.title=法杖
journal.catalog.rings.title=戒指
journal.catalog.artifacts.title=神器
journal.catalog.trinkets.title=飾品
journal.catalog.misc_equipment.title=雜項裝備

journal.catalog.potions.title=藥水
journal.catalog.scrolls.title=卷軸
journal.catalog.seeds.title=種子
journal.catalog.stones.title=符石
journal.catalog.food.title=食物
journal.catalog.exotic_scrolls.title=秘卷
journal.catalog.bombs.title=炸彈
journal.catalog.tipped_darts.title=塗藥飛鏢
journal.catalog.spells.title=法術
journal.catalog.misc_consumables.title=雜項消耗品


journal.document.adventurers_guide.title=地城探索指南
journal.document.adventurers_guide.intro.title=基礎介紹
journal.document.adventurers_guide.intro.body=歡迎，冒險家，你正在閱讀地城探索指南。本手冊包含著能幫助新手冒險家存活並精進能力的所有提示與技巧!\n\n本手冊做為參考用的魔法指南，它會在適當的時機讓你知道你應該讀哪個部分以解決當前情況。\n\n(當右上方日誌鈕發亮時，就代表著指南有事要告訴你! 有些頁面鬆脫了，可能散落在地下城中?)


journal.document.intros.dungeon.body=在你之前已有許多英雄自上方的城市進入這座地下城探索，大多數都已音訊全無。\n\n據說地下城深處藏著古老的邪惡力量，守護著全能的Yender護符。就連到現在都還有黑暗能量從底下竄出，朝著城市前進。\n\n你究竟能不能拿下這座地下城並奪得護符呢? 是時候開始屬於你的冒險了!






journal.notes$landmark.shop=商店
journal.notes$landmark.alchemy=鍊金釜
journal.notes$landmark.garden=靜謐花圃
journal.notes$landmark.distant_well=遠處的井
journal.notes$landmark.well_of_health=生命之泉
journal.notes$landmark.sacrificial_fire=獻祭烈焰
journal.notes$landmark.rat_king=鼠王
journal.notes$landmark.troll=巨魔鐵匠
journal.notes$landmark.demon_spawner=惡魔血巢
