journal.bestiary.regional.title=regional enemies
journal.bestiary.bosses.title=regional bosses
journal.bestiary.universal.title=universal enemies
journal.bestiary.rare.title=rare enemies
journal.bestiary.quest.title=quest enemies & bosses
journal.bestiary.neutral.title=neutral characters
journal.bestiary.ally.title=allies
journal.bestiary.trap.title=traps
journal.bestiary.plant.title=plants

journal.catalog.melee_weapons.title=melee weapons
journal.catalog.armor.title=armor
journal.catalog.enchantments.title=enchantments and curses
journal.catalog.glyphs.title=glyphs and curses
journal.catalog.thrown_weapons.title=thrown weapons
journal.catalog.wands.title=wands
journal.catalog.rings.title=rings
journal.catalog.artifacts.title=artifacts
journal.catalog.trinkets.title=trinkets
journal.catalog.misc_equipment.title=misc. equipment

journal.catalog.potions.title=potions
journal.catalog.scrolls.title=scrolls
journal.catalog.seeds.title=seeds
journal.catalog.stones.title=runestones
journal.catalog.food.title=food
journal.catalog.exotic_scrolls.title=exotic scrolls
journal.catalog.bombs.title=bombs
journal.catalog.tipped_darts.title=tipped darts
journal.catalog.spells.title=spells
journal.catalog.misc_consumables.title=misc. consumables


journal.document.adventurers_guide.title=Tome of Dungeon Mastery
journal.document.adventurers_guide.intro.title=Introduction
journal.document.adventurers_guide.intro.body=Greetings Adventurer, you are reading the Tome of Dungeon Mastery! This guidebook is best used as a reference, and will magically let you know when it's best to read each page.\n\n(When the journal button flashes, select it to read what the guidebook has to tell you! Some pages are missing though, perhaps you can find them in the dungeon?)


journal.document.intros.dungeon.body=Many heroes have ventured into the dungeon before you from the city above, most have never been heard from again.\n\nIt is said that an ancient evil lurks in the depths, guarding the almighty Amulet of Yendor. Even now dark energy radiates from below, making its way up into the city.\n\nWill you conquer the dungeon and claim the amulet? It's time to start your own adventure!






journal.notes$landmark.shop=shop
journal.notes$landmark.alchemy=alchemy pot
journal.notes$landmark.garden=garden
journal.notes$landmark.distant_well=distant well
journal.notes$landmark.well_of_health=well of health
journal.notes$landmark.sacrificial_fire=sacrificial fire
journal.notes$landmark.rat_king=rat king
journal.notes$landmark.troll=troll blacksmith
journal.notes$landmark.demon_spawner=demon spawner
